In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
ocorrencia=pd.read_csv('ocorrencia.csv', sep = ';')
ocorrencia

,codigo_ocorrencia,codigo_ocorrencia1,codigo_ocorrencia2,codigo_ocorrencia3,codigo_ocorrencia4,ocorrencia_classificacao,ocorrencia_latitude,ocorrencia_longitude,ocorrencia_cidade,ocorrencia_uf,...,ocorrencia_dia,ocorrencia_hora,investigacao_aeronave_liberada,investigacao_status,divulgacao_relatorio_numero,divulgacao_relatorio_publicado,divulgacao_dia_publicacao,total_recomendacoes,total_aeronaves_envolvidas,ocorrencia_saida_pista
0,52242,52242,52242,52242,52242,INCIDENTE,NaN,NaN,PORTO ALEGRE,RS,...,05/01/2012,20:27:00,***,FINALIZADA,***,NÃO,NaN,0,1,NÃO
1,45331,45331,45331,45331,45331,ACIDENTE,-23.4355555556,-46.4730555556,GUARULHOS,SP,...,06/01/2012,13:44:00,SIM,FINALIZADA,A-582/CENIPA/2014,SIM,2016-09-01,3,1,NÃO
2,45333,45333,45333,45333,45333,ACIDENTE,***,***,VIAMÃO,RS,...,06/01/2012,13:00:00,NaN,FINALIZADA,A-070/CENIPA/2013,SIM,2013-11-27,0,1,NÃO
3,45401,45401,45401,45401,45401,ACIDENTE,***,***,SÃO SEBASTIÃO,SP,...,06/01/2012,17:00:00,***,NaN,NaN,NÃO,NaN,0,1,NÃO
4,45407,45407,45407,45407,45407,ACIDENTE,***,***,SÃO SEPÉ,RS,...,06/01/2012,16:30:00,SIM,FINALIZADA,A-071/CENIPA/2013,SIM,2013-11-27,0,1,NÃO
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5162,80458,80458,80458,80458,80458,ACIDENTE,-17.999194,-51.642861,JATAÍ,GO,...,30/12/2021,20:30:00,SIM,ATIVA,A DEFINIR,NÃO,NaN,0,1,NÃO
5163,80452,80452,80452,80452,80452,ACIDENTE,-22.585556,-50.753889,MARACAÍ,SP,...,31/12/2021,09:30:00,SIM,ATIVA,A DEFINIR,NÃO,NaN,0,1,NÃO
5164,80457,80457,80457,80457,80457,INCIDENTE GRAVE,-29.695833,-51.081667,NOVO HAMBURGO,RS,...,31/12/2021,11:59:00,SIM,FINALIZADA,***,NÃO,NaN,0,1,NÃO
5165,80460,80460,80460,80460,80460,INCIDENTE,-25.403333,-49.233611,CURITIBA,PR,...,31/12/2021,15:12:00,SIM,FINALIZADA,***,NÃO,NaN,0,1,NÃO
5166,80467,80467,80467,80467,80467,INCIDENTE,-9.3675,-40.56361111111,PETROLINA,PE,...,31/12/2021,20:30:00,SIM,FINALIZADA,***,NÃO,NaN,0,1,NÃO

In [5]:
ocorrencias_filtradas = ocorrencia.loc[:,['codigo_ocorrencia1', 'ocorrencia_classificacao', 'ocorrencia_cidade', 'ocorrencia_uf', 'ocorrencia_aerodromo', 'ocorrencia_dia', 'ocorrencia_hora']]
ocorrencias_filtradas[['Dia','Mes', 'Ano']] = ocorrencias_filtradas.ocorrencia_dia.str.split("/",expand=True,)
ocorrencias_filtradas

,codigo_ocorrencia1,ocorrencia_classificacao,ocorrencia_cidade,ocorrencia_uf,ocorrencia_aerodromo,ocorrencia_dia,ocorrencia_hora,Dia,Mes,Ano
0,52242,INCIDENTE,PORTO ALEGRE,RS,SBPA,05/01/2012,20:27:00,05,01,2012
1,45331,ACIDENTE,GUARULHOS,SP,SBGR,06/01/2012,13:44:00,06,01,2012
2,45333,ACIDENTE,VIAMÃO,RS,****,06/01/2012,13:00:00,06,01,2012
3,45401,ACIDENTE,SÃO SEBASTIÃO,SP,****,06/01/2012,17:00:00,06,01,2012
4,45407,ACIDENTE,SÃO SEPÉ,RS,****,06/01/2012,16:30:00,06,01,2012
...,...,...,...,...,...,...,...,...,...,...
5162,80458,ACIDENTE,JATAÍ,GO,####,30/12/2021,20:30:00,30,12,2021
5163,80452,ACIDENTE,MARACAÍ,SP,*****,31/12/2021,09:30:00,31,12,2021
5164,80457,INCIDENTE GRAVE,NOVO HAMBURGO,RS,SSNH,31/12/2021,11:59:00,31,12,2021
5165,80460,INCIDENTE,CURITIBA,PR,SBBI,31/12/2021,15:12:00,31,12,2021
5166,80467,INCIDENTE,PETROLINA,PE,SBPL,31/12/2021,20:30:00,31,12,2021

In [ ]:
aeronaves